---
permalink: sm-storage/change-configuration-settings-for-a-pool.html 
sidebar: sidebar 
keywords: change, configuration, set, pool 
summary: Sie können die Einstellungen für einen Pool bearbeiten, wenn Sie seinen Namen ändern, die Einstellungen für Kapazitätswarnungen, seine Änderungsprioritäten oder die Erhaltungskapazität bearbeiten möchten. 
---
= Ändern Sie die Konfigurationseinstellungen für einen Pool
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Einstellungen für einen Pool bearbeiten, wenn Sie seinen Namen ändern, die Einstellungen für Kapazitätswarnungen, seine Änderungsprioritäten oder die Erhaltungskapazität bearbeiten möchten.

.Schritte
. Wählen Sie *menu:Speicher[Pools & Volume Groups]*.
. Wählen Sie den Pool aus, den Sie bearbeiten möchten, und klicken Sie dann auf *Einstellungen anzeigen/bearbeiten*.
+
Das Dialogfeld *Pool-Einstellungen* wird angezeigt.

. Wählen Sie die Registerkarte *Einstellungen* aus, und bearbeiten Sie anschließend die Pooleinstellungen entsprechend.
+
.Felddetails
[%collapsible]
====
[cols="2*"]
|===
| Einstellung | Beschreibung 


 a| 
Name
 a| 
Sie können den vom Benutzer bereitgestellten Namen des Pools ändern. Die Angabe eines Namens für einen Pool ist erforderlich.



 a| 
Kapazitätswarnungen
 a| 
Sie können Benachrichtigungen senden, wenn die freie Kapazität in einem Pool einen bestimmten Schwellenwert erreicht oder überschreitet. Wenn die im Pool gespeicherten Daten den angegebenen Schwellenwert überschreiten, sendet System Manager eine Meldung, sodass Sie mehr Speicherplatz hinzufügen oder unnötige Objekte löschen können.

Warnmeldungen werden im Bereich Benachrichtigungen auf dem Dashboard angezeigt und können per E-Mail und SNMP-Trap-Nachrichten vom Server an Administratoren gesendet werden.

Sie können die folgenden Kapazitätswarnungen definieren:

** *Critical Alert* -- Diese kritische Warnmeldung informiert Sie, wenn die freie Kapazität im Pool den angegebenen Schwellenwert erreicht oder überschreitet. Verwenden Sie die Spinner-Regler, um den Schwellenwert in Prozent einzustellen. Aktivieren Sie das Kontrollkästchen, um diese Benachrichtigung zu deaktivieren.
** *Frühwarnung* -- Diese Frühwarnung informiert Sie, wenn die freie Kapazität in einem Pool einen bestimmten Schwellenwert erreicht. Verwenden Sie die Spinner-Regler, um den Schwellenwert in Prozent einzustellen. Aktivieren Sie das Kontrollkästchen, um diese Benachrichtigung zu deaktivieren.




 a| 
Änderungsprioritäten
 a| 
Sie können die Prioritätsstufen für Änderungsvorgänge in einem Pool relativ zur Systemleistung festlegen. Eine höhere Priorität für Änderungsvorgänge in einem Pool führt dazu, dass ein Vorgang schneller abgeschlossen wird, die Host-I/O-Performance jedoch beeinträchtigt wird. Bei geringerer Priorität dauern Vorgänge länger, bis die I/O-Performance des Hosts weniger beeinträchtigt ist.

Sie können aus fünf Prioritätsstufen wählen: Niedrigste, niedrige, mittlere, höchste und höchste. Je höher die Priorität, desto größer ist die Auswirkung auf die Host-I/O und System-Performance.

** *Kritische Rekonstruktionspriorität* -- dieser Schieberegler bestimmt die Priorität eines Datenrekonstruktionsvorgangs, wenn mehrere Laufwerksausfälle zu einem Zustand führen, in dem einige Daten keine Redundanz aufweisen und ein zusätzlicher Laufwerksausfall zu Datenverlust führen kann.
** *Degradierte Rekonstruktionspriorität* -- dieser Schieberegler bestimmt die Priorität des Datenrekonstruktionsvorgangs bei einem Laufwerksausfall, aber die Daten haben noch Redundanz und ein zusätzlicher Laufwerksausfall führt nicht zu Datenverlust.
** *Background Operation Priority* -- dieser Schieberegler bestimmt die Priorität der Pool-Hintergrundoperationen, die auftreten, während sich der Pool in einem optimalen Zustand befindet. Zu diesen Vorgängen gehören dynamische Volume-Erweiterung (DVE), Instant Availability Format (IAF) und die Migration von Daten auf ein ersetztes oder hinzugefügtes Laufwerk.




 a| 
Erhaltungskapazität
 a| 
Sie können die Anzahl der Laufwerke festlegen, um die Kapazität zu bestimmen, die im Pool reserviert ist, um potenzielle Laufwerksausfälle zu unterstützen. Bei einem Laufwerksausfall werden die rekonstruierten Daten anhand der Festplattenkapazität gespeichert. Pools verwenden während der Datenrekonstruktion freie Kapazitäten anstelle von Hot-Spare-Laufwerken, die in Volume-Gruppen verwendet werden.

Passen Sie mit den Spinner-Steuerungen die Anzahl der Antriebe an. Je nach Anzahl der Laufwerke wird die Konservierungskapazität im Pool neben der Spinner Box angezeigt.

Berücksichtigen Sie die folgenden Hinweise zur Konservierungskapazität.

** Da die Konservierungskapazität von der gesamten freien Kapazität eines Pools abgezogen wird, wirkt sich die Menge der reservierten Kapazität darauf aus, wie viel freie Kapazität zur Erstellung von Volumes zur Verfügung steht. Wenn Sie für die Erhaltungskapazität 0 angeben, wird die gesamte freie Kapazität im Pool zur Volume-Erstellung genutzt.
** Wenn Sie die Konservierungskapazität verringern, erhöhen Sie die Kapazität, die für Pool Volumes genutzt werden kann.


|===
====
. Klicken Sie Auf *Speichern*.

