---
permalink: sm-storage/what-is-data-assurance.html 
sidebar: sidebar 
keywords: data, assurance 
summary: 'Data Assurance (da) überprüft und korrigiert Fehler, die auftreten können, wenn Daten zwischen einem Host und einem Storage-Array übermittelt werden. DA-Funktionen werden auf Pool- und Volume-Gruppenebene in System Manager präsentiert.' 
---
= Was ist Data Assurance?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Data Assurance (da) überprüft und korrigiert Fehler, die auftreten können, wenn Daten zwischen einem Host und einem Storage-Array übermittelt werden. DA-Funktionen werden auf Pool- und Volume-Gruppenebene in System Manager präsentiert.

Die Data Assurance (da)-Funktion erhöht die Datenintegrität im gesamten Storage-System. DA ermöglicht es dem Storage-Array, nach Fehlern zu suchen, die auftreten können, wenn Daten zwischen Hosts und Laufwerken verschoben werden. Wenn diese Funktion aktiviert ist, hängt das Speicherarray die Fehlerprüfungscodes (auch zyklische Redundanzprüfungen oder CRCs genannt) an jeden Datenblock im Volume an. Nach dem Verschieben eines Datenblocks ermittelt das Speicher-Array anhand dieser CRC-Codes, ob während der Übertragung Fehler aufgetreten sind. Potenziell beschädigte Daten werden weder auf Festplatte geschrieben noch an den Host zurückgegeben.

Wenn Sie die da-Funktion verwenden möchten, wählen Sie einen Pool oder eine Volume-Gruppe aus, die bei der Erstellung eines neuen Volumes unterstützt wird (suchen Sie in der Tabelle „Kandidaten für Pool und Volume-Gruppen“ nach *Ja* neben da).

Stellen Sie sicher, dass Sie diese DA-fähigen Volumes einem Host über eine E/A-Schnittstelle zuweisen, die über eine da-fähige Schnittstelle verfügt. Zu den I/O-Schnittstellen, die da fähig sind, gehören Fibre Channel, SAS, iSCSI über TCP/IP und iSER over InfiniBand (iSCSI-Erweiterungen für RDMA/IB). DA wird von SRP nicht über InfiniBand unterstützt.
