---
permalink: sm-mirroring/asynchronous-mirroring-why-dont-i-see-all-the-volumes-on-the-remote-storage-array.html 
sidebar: sidebar 
keywords: asynchronous, mirror, all my volumes, remote storage array 
summary: Wenn Sie ein sekundäres Volume auf dem Remote-Speicher-Array auswählen, zeigt System Manager eine Liste aller berechtigten Volumes für dieses gespiegelte Paar an. Alle Volumes, die nicht für die Verwendung geeignet sind, werden in dieser Liste nicht angezeigt. 
---
= Asynchrones Spiegeln - Warum sehe ich nicht alle Volumen auf dem Remote-Speicher-Array?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein sekundäres Volume auf dem Remote-Speicher-Array auswählen, zeigt System Manager eine Liste aller berechtigten Volumes für dieses gespiegelte Paar an. Alle Volumes, die nicht für die Verwendung geeignet sind, werden in dieser Liste nicht angezeigt.

Die Volumes können aus den folgenden Gründen nicht berechtigt sein:

* Das Volume ist ein nicht standardmäßiges Volume, wie z. B. ein Snapshot-Volume.
* Die Lautstärke ist nicht optimal.
* Das Volume beteiligt sich bereits an einer Spiegelbeziehung.
* Die Thin-Volume-Attribute des primären Volume und des sekundären Volumes stimmen nicht überein.
* Wenn Sie Data Assurance (da) verwenden, müssen das primäre Volume und das sekundäre Volume über dieselben da-Einstellungen verfügen.
+
** Wenn das primäre Volume mit da aktiviert ist, muss das sekundäre Volume mit da aktiviert sein.
** Wenn das primäre Volume nicht da aktiviert ist, darf das sekundäre Volume nicht als da-aktiviert verwendet werden.



