---
permalink: sm-mirroring/requirements-for-using-synchronous-mirroring.html 
sidebar: sidebar 
keywords: requirements, synchronous, mirroring 
summary: Wenn Sie die Funktion Synchronous Mirroring verwenden, beachten Sie bitte die folgenden Anforderungen. 
---
= Anforderungen für die Nutzung von synchroner Spiegelung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die Funktion Synchronous Mirroring verwenden, beachten Sie bitte die folgenden Anforderungen.



== SANtricity Unified Manager

Da die Funktion zur synchronen Spiegelung das Management mehrerer Storage Arrays erfordert, ist der browserbasierte SANtricity Unified Manager installiert. Damit sind die beiden Storage-Arrays, zwischen denen Daten gespiegelt werden sollen, bekannt. Wählen Sie dann im Unified Manager das Storage-Array des primären Volumes aus und klicken Sie auf Start, um den browserbasierten SANtricity System Manager zu öffnen.



== Storage-Arrays durchführt

* Sie müssen über zwei Storage-Arrays verfügen.
* Jedes Speicher-Array muss zwei Controller haben.
* Auf den Speicher-Arrays der primären und sekundären Volumes können unterschiedliche Betriebssystemversionen ausgeführt werden. Die unterstützte Mindestversion ist 7.84.
* Sie müssen das Passwort für die lokalen und Remote-Speicher-Arrays kennen.
* Sie benötigen genügend freie Kapazität auf dem Remote-Speicher-Array, um ein sekundäres Volume zu erstellen, das dem primären Volume entspricht oder dessen Größe Sie spiegeln möchten.
* Ihre lokalen und Remote-Speicher-Arrays müssen über eine Fibre Channel Fabric verbunden sein.




== Unterstützte Hardwarekonfiguration und -Verbindungen

* Synchrones Spiegeln wird nur in Hardware-Konfigurationen mit Dual Controllern unterstützt.
* Kommunikation für synchrones Spiegeln wird nur auf Controllern mit Fibre Channel (FC) Host Ports unterstützt.
* Bei der synchronen Spiegelung wird der am höchsten nummerierte Host Port auf jedem Controller verwendet, sowohl auf dem lokalen Storage-Array als auch auf dem Remote-Storage-Array. Der Controller Host Bus Adapter (HBA) Host-Port 4 ist normalerweise für die Übertragung von Spiegeldaten reserviert.




== Kandidaten für gespiegelte Volumes

* RAID-Level, Caching-Parameter und Segmentgröße können auf den primären und sekundären Volumes eines synchronen gespiegelten Paars unterschiedlich sein.
* Die primären und sekundären Volumes in einem synchronen gespiegelten Paar müssen Standard-Volumes sein. Es können keine dünnen Volumes oder Snapshot Volumes sein.
* Das sekundäre Volume muss mindestens so groß sein wie das primäre Volume.
* Mit dem primären Volume sind möglicherweise nur Snapshots verknüpft, und/oder das Quell- oder Ziel-Volume während eines Volume-Kopiervorgangs.
* Ein Volume kann nur an einer Spiegelbeziehung beteiligt sein.




== Reservierte Kapazität

* Für ein primäres Volume und ein sekundäres Volume zur Protokollierung von Schreibinformationen zum Wiederherstellen nach Controller-Resets und anderen vorübergehenden Unterbrechungen ist die reservierte Kapazität erforderlich.
* Die reservierten Kapazitäts-Volumes werden automatisch bei aktivierter synchronen Spiegelung erstellt. Da sowohl das primäre Volume als auch das sekundäre Volume in einem gespiegelten Paar reservierte Kapazität benötigen, müssen Sie sicherstellen, dass auf beiden Storage-Arrays, die an der Beziehung zur synchronen Spiegelung beteiligt sind, ausreichend freie Kapazität zur Verfügung steht.




== Laufwerkssicherheit

* Wenn Sie sichere Laufwerke verwenden, müssen das primäre und das sekundäre Volume über kompatible Sicherheitseinstellungen verfügen. Diese Beschränkung wird nicht durchgesetzt, deshalb müssen Sie sie selbst überprüfen.
* Bei Verwendung von sicheren Laufwerken sollten das primäre Volume und das sekundäre Volume denselben Laufwerkstyp verwenden. Diese Beschränkung wird nicht durchgesetzt, deshalb müssen Sie sie selbst überprüfen.
+
** Wenn das primäre Volume vollständige Festplattenverschlüsselung (Full Disk Encryption, FDE) verwendet, sollten auf dem sekundären Volume FDE-Laufwerke verwendet werden.
** Wenn das primäre Volume gemäß FIPS (Federal Information Processing Standards 140-2) zertifizierte Laufwerke verwendet, sollte auf dem sekundären Volume FIPS 140-2-2-zertifizierte Laufwerke verwendet werden.


* Wenn Sie Data Assurance (da) verwenden, müssen das primäre Volume und das sekundäre Volume über dieselben da-Einstellungen verfügen.

