---
permalink: sm-mirroring/synchronous-mirroring-what-do-i-need-to-know-before-creating-a-mirrored-pair.html 
sidebar: sidebar 
keywords: synchronous, mirroring, create, mirrored path 
summary: Bevor Sie ein gespiegeltes Paar erstellen, stellen Sie sicher, dass Ihre Umgebung die folgenden Richtlinien erfüllt. 
---
= Synchrones Spiegeln - Was muss ich wissen, bevor ein gespiegeltes Paar erstellt wird?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie ein gespiegeltes Paar erstellen, stellen Sie sicher, dass Ihre Umgebung die folgenden Richtlinien erfüllt.

* Sie benötigen genügend freie Kapazität auf dem Remote-Speicher-Array, um ein sekundäres Volume zu erstellen, das dem primären Volume entspricht oder dessen Größe Sie spiegeln möchten.
* Sie müssen über zwei Storage-Arrays verfügen.
* Jedes Speicher-Array muss zwei Controller haben.
* Sie müssen das Passwort für die lokalen und Remote-Speicher-Arrays kennen.
* Ihre lokalen und Remote-Speicher-Arrays müssen über eine Fibre Channel Fabric verbunden sein.
* Sie müssen die beiden Speicher-Arrays entdeckt haben, zwischen denen Daten gespiegelt werden sollen. Wählen Sie dann im Unified Manager das Storage-Array des primären Volumes aus und klicken Sie auf Start, um den browserbasierten SANtricity System Manager zu öffnen.

