---
permalink: sm-hardware/configure-iser-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: configure, iser, infiniband, ports 
summary: Wenn der Controller einen iSER-over-InfiniBand-Port enthält, können Sie die Netzwerkverbindung zu dem Host konfigurieren. Die Konfigurationseinstellungen sind auf der Seite Hardware oder auf der Seite System verfügbar. 
---
= Konfigurieren Sie iSER-over-InfiniBand-Ports
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn der Controller einen iSER-over-InfiniBand-Port enthält, können Sie die Netzwerkverbindung zu dem Host konfigurieren. Die Konfigurationseinstellungen sind auf der Seite Hardware oder auf der Seite System verfügbar.

.Bevor Sie beginnen
* Der Controller muss einen iSER-over-InfiniBand-Port umfassen, andernfalls sind die iSER-over-InfiniBand-Einstellungen in System Manager nicht verfügbar.
* Sie müssen die IP-Adresse der Hostverbindung kennen.


.Über diese Aufgabe
Sie können über die Seite *Hardware* oder über Menü:Einstellungen[System] auf die Konfiguration iSER-over-InfiniBand zugreifen. Diese Aufgabe beschreibt die Konfiguration der Ports auf der Seite *Hardware*.

[NOTE]
====
Die iSER-over-InfiniBand-Einstellungen und -Funktionen werden nur angezeigt, wenn der Controller Ihres Storage-Arrays einen iSER-over-InfiniBand-Port umfasst.

====
.Schritte
. Wählen Sie *Hardware*.
. Wenn die Grafik die Laufwerke anzeigt, klicken Sie auf *Zurück zum Regal anzeigen*.
+
Die Grafik ändert sich, um die Controller anstelle der Laufwerke anzuzeigen.

. Klicken Sie auf den Controller mit dem iSER-over-InfiniBand-Port, den Sie konfigurieren möchten.
+
Das Kontextmenü des Controllers wird angezeigt.

. Wählen Sie *iSER-over-InfiniBand-Ports konfigurieren*.
+
Das Dialogfeld *iSER über InfiniBand Ports konfigurieren* wird geöffnet.

. Wählen Sie in der Dropdown-Liste den HIC-Port aus, den Sie konfigurieren möchten, und geben Sie dann die IP-Adresse des Hosts ein.
. Klicken Sie Auf *Konfigurieren*.
. Vervollständigen Sie die Konfiguration, und setzen Sie dann den iSER-over-InfiniBand-Port zurück, indem Sie auf *Ja* klicken.

