---
permalink: sm-settings/configure-nvme-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, infiniband, ports 
summary: Wenn Ihr Controller eine NVMe-over-InfiniBand-Verbindung enthält, können Sie die NVMe-Port-Einstellungen auf der Seite Hardware oder auf der System-Seite konfigurieren. 
---
= Konfigurieren Sie NVMe-over-InfiniBand-Ports
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihr Controller eine NVMe-over-InfiniBand-Verbindung enthält, können Sie die NVMe-Port-Einstellungen auf der Seite Hardware oder auf der System-Seite konfigurieren.

.Bevor Sie beginnen
* Der Controller muss einen NVMe-over-InfiniBand-Host-Port enthalten. Andernfalls stehen die NVMe-over-InfiniBand-Einstellungen in System Manager nicht zur Verfügung.
* Sie müssen die IP-Adresse der Hostverbindung kennen.


Sie können die NVMe over InfiniBand-Konfiguration über die Seite *Hardware* oder über das Menü:Einstellungen[System] aufrufen. Diese Aufgabe beschreibt die Konfiguration der Ports auf der Seite *Hardware*.

[NOTE]
====
Die NVMe-over-InfiniBand-Einstellungen und -Funktionen werden nur angezeigt, wenn der Controller des Storage-Arrays einen NVMe-over-InfiniBand-Port enthält.

====
.Schritte
. Wählen Sie *Hardware*.
. Wenn die Grafik die Laufwerke anzeigt, klicken Sie auf *Zurück zum Regal anzeigen*.
+
Die Grafik ändert sich, um die Controller anstelle der Laufwerke anzuzeigen.

. Klicken Sie auf den Controller mit dem NVMe over InfiniBand-Port, den Sie konfigurieren möchten.
+
Das Kontextmenü des Controllers wird angezeigt.

. Wählen Sie *NVMe über InfiniBand-Ports konfigurieren* aus.
+
Das Dialogfeld *NVMe über InfiniBand Ports konfigurieren* wird geöffnet.

. Wählen Sie in der Dropdown-Liste den HIC-Port aus, den Sie konfigurieren möchten, und geben Sie dann die IP-Adresse des Hosts ein.
. Klicken Sie Auf *Konfigurieren*.
. Führen Sie die Konfiguration aus, und setzen Sie den NVMe over InfiniBand-Port zurück, indem Sie auf *Ja* klicken.

