---
permalink: sm-settings/import-trusted-certificates-for-controllers-acting-as-client.html 
sidebar: sidebar 
keywords: import, trusted, certificates, controllers 
summary: 'Nachdem Sie digitale Zertifikate von einer Zertifizierungsstelle (CA) erhalten haben, können Sie die Zertifikatskette (Zwischen- und Stammverzeichnis) für die Controller importieren.' 
---
= Vertrauenswürdige Zertifikate für Controller importieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie digitale Zertifikate von einer Zertifizierungsstelle (CA) erhalten haben, können Sie die Zertifikatskette (Zwischen- und Stammverzeichnis) für die Controller importieren.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das Sicherheitsadministratorberechtigungen enthält. Andernfalls werden keine Zertifikatfunktionen angezeigt.
* Sie haben eine Anfrage zur Zertifikatssignierung (.CSR-Datei) erstellt und an die CA gesendet.
* Die CA hat vertrauenswürdige Zertifikatdateien zurückgegeben.
* Die Zertifikatdateien werden auf Ihrem lokalen System installiert.


In dieser Aufgabe wird beschrieben, wie Sie die vertrauenswürdigen Zertifikate für die Controller des Speicherarrays hochladen.

.Schritte
. Wählen Sie Menü:Einstellungen[Zertifikate].
. Wählen Sie auf der Registerkarte * Trusted* die Option *Import* aus.
+
Es wird ein Dialogfeld zum Importieren der vertrauenswürdigen Zertifikatdateien geöffnet.

. Klicken Sie auf *Durchsuchen*, um die Zertifikatdateien für die Controller auszuwählen.
+
Die Dateinamen werden im Dialogfeld angezeigt.

. Klicken Sie Auf *Import*.


Die Dateien werden hochgeladen und validiert.

Importieren Sie das Managementzertifikat.
