---
permalink: sm-settings/reset-management-certificates.html 
sidebar: sidebar 
keywords: reset, management, certificates 
summary: Sie können die Managementzertifikate auf dem Speicher-Array wieder in den werkseitig selbstsignierten Status zurücksetzen. 
---
= Managementzertifikate zurücksetzen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Managementzertifikate auf dem Speicher-Array wieder in den werkseitig selbstsignierten Status zurücksetzen.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das Sicherheitsadministratorberechtigungen enthält. Andernfalls werden keine Zertifikatfunktionen angezeigt.
* Zertifikate müssen bereits importiert werden.


.Über diese Aufgabe
Durch das Zurücksetzen der Managementzertifikate auf dem Speicher-Array werden die aktuellen Managementzertifikate von jedem der Controller gelöscht. Nach dem Zurücksetzen der Zertifikate werden die Controller mit selbstsignierten Zertifikaten zurückgesetzt.

.Schritte
. Wählen Sie Menü:Einstellungen[Zertifikate].
. Wählen Sie auf der Registerkarte *Array Management* die Option *Zurücksetzen*.
+
Das Dialogfeld „Management-Zertifikate zurücksetzen bestätigen*“ wird geöffnet.

. Typ `reset` Klicken Sie im Feld auf *Zurücksetzen*.


.Ergebnisse
Nach der Aktualisierung des Browsers werden die Controller mithilfe von selbstsignierten Zertifikaten wiederhergestellt. Das System fordert Benutzer daher auf, das selbstsignierte Zertifikat für ihre Sitzungen manuell anzunehmen.
