---
permalink: sm-settings/step-3-import-signed-certificates-for-the-controllers.html 
sidebar: sidebar 
keywords: import, management, certificate, controllers 
summary: 'Nach dem Import der vertrauenswürdigen Zertifikatskette importieren Sie für jeden Controller im Speicher-Array eine Management (signierte) Zertifikatdatei.' 
---
= Importieren Sie ein Managementzertifikat für Controller
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Import der vertrauenswürdigen Zertifikatskette importieren Sie für jeden Controller im Speicher-Array eine Management (signierte) Zertifikatdatei.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das Sicherheitsadministratorberechtigungen enthält. Andernfalls werden keine Zertifikatfunktionen angezeigt.
* Die vertrauenswürdigen Zertifikate wurden importiert.
* Die CA hat für jeden Controller eine Management-Zertifikatdatei zurückgegeben.
* Die Managementzertifikatdatei(en) stehen auf Ihrem lokalen System zur Verfügung.


.Über diese Aufgabe
In dieser Aufgabe wird beschrieben, wie Sie die Management-Zertifikatdateien für die Controller-Authentifizierung hochladen.

.Schritte
. Wählen Sie Menü:Einstellungen[Zertifikate].
. Wählen Sie auf der Registerkarte *Array Management* die Option *Import*.
+
Es wird ein Dialogfeld zum Importieren der Zertifikatdatei(en) geöffnet.

. Klicken Sie auf *Durchsuchen*, um die Datei für Controller A. auszuwählen Wenn es zwei Controller gibt, klicken Sie auf die zweite Schaltfläche *Durchsuchen*, um die Datei für Controller B auszuwählen
+
Die Dateinamen werden im Dialogfeld angezeigt.

. Klicken Sie Auf *Import*.
+
Die Datei(en) werden hochgeladen und validiert.



.Ergebnisse
Die Sitzung wird automatisch beendet. Sie müssen sich erneut anmelden, damit die Zertifikate wirksam werden. Wenn Sie sich erneut anmelden, wird das neue CA-signierte Zertifikat für Ihre Sitzung verwendet.
