---
permalink: sm-settings/what-is-cache-block-size.html 
sidebar: sidebar 
keywords: what, cache, block, size 
summary: Der Controller des Speicherarrays organisiert seinen Cache in Blöcke, die Speicherblöcke sind, die 4, 8, 16 oder 32 KiBs groß sein können. Alle Volumes im Storage-System nutzen denselben Cache-Speicherplatz. Daher können die Volumes nur eine Cache-Blockgröße aufweisen. 
---
= Was ist die Cache-Blockgröße?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Controller des Storage Arrays ordnet den Cache in „Blöcke“ zu. Dabei handelt es sich um Speicherblöcke mit einer Größe von 4, 8, 16 oder 32 KiBs. Alle Volumes im Storage-System nutzen denselben Cache-Speicherplatz. Daher können die Volumes nur eine Cache-Blockgröße aufweisen.

[NOTE]
====
Cache-Blöcke sind nicht mit 512-Byte-Blöcken identisch, die vom logischen Block-System der Festplatten verwendet werden.

====
Applikationen verwenden unterschiedliche Blockgrößen, die wiederum einen Einfluss auf die Storage-Performance haben können. Standardmäßig ist die Blockgröße in System Manager 8 KiB, Sie können den Wert jedoch auf 4, 8, 16 oder 32 KiBs festlegen. Kleinere Größen sind eine gute Wahl für Dateisysteme oder Datenbankanwendungen. Eine größere Größe ist eine gute Wahl für Applikationen, die eine umfangreiche Datenübertragung, sequenziellen I/O oder eine hohe Bandbreite, wie z. B. Multimedia, erfordern.
