---
permalink: sm-support/view-nvme-over-infiniband-statistics-support.html 
sidebar: sidebar 
keywords: view, nvme, infiniband, statistics, packages 
summary: Daten zu den NVMe-over-InfiniBand-Verbindungen können mit dem Storage-Array angezeigt werden. 
---
= Anzeigen von NVMe-over-InfiniBand-Statistikpaketen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Daten zu den NVMe-over-InfiniBand-Verbindungen können mit dem Storage-Array angezeigt werden.

.Über diese Aufgabe
System Manager zeigt diese NVMe-over-InfiniBand-Statistiken. Alle Statistiken sind schreibgeschützt und können nicht festgelegt werden.

* *NVMe-Controller-Statistiken* -- liefert Statistiken für den NVMe-Controller, einschließlich Timeouts und Verbindungsfehlern.
* *NVMe Queue Statistics* -- liefert Statistiken für die NVMe-Warteschlange, einschließlich Verbindungsanfragen und Befehlsstatus.


Sie können jede dieser Statistiken als RAW-Statistiken oder als Baseline-Statistiken anzeigen. RAW-Statistiken sind alle Statistiken, die seit dem Start der Controller gesammelt wurden. Baseline-Statistiken sind zeitpunktgenaue Statistiken, die seit dem Festlegen der Baseline-Zeit erfasst wurden.

Sie können über die Systemseite (Menü:Einstellungen[System]) oder über die Support-Seite auf die NVMe-over-InfiniBand-Statistiken zugreifen. In diesen Anweisungen wird der Zugriff auf die Statistiken auf der Support-Seite beschrieben.

.Schritte
. Wählen Sie MENU:Support[Support Center > Diagnose].
. Wählen Sie *NVMe über InfiniBand Statistikpakete anzeigen*.
. Klicken Sie zum Festlegen des Basisplans auf *Neue Baseline festlegen*.
+
Durch das Festlegen der Baseline wird ein neuer Ausgangspunkt für die Erfassung der Statistiken festgelegt. Dieselbe Baseline wird für alle NVMe-Statistiken verwendet.


