---
permalink: sm-support/view-nvme-over-fabrics-statistics-support.html 
sidebar: sidebar 
keywords: view, nvme, fabrics, statistics 
summary: Daten über die NVMe over Fabrics-Verbindungen mit Ihrem Storage-Array anzeigen lassen, 
---
= Anzeigen der NVMe over Fabrics Statistiken
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Daten über die NVMe over Fabrics-Verbindungen mit Ihrem Storage-Array anzeigen lassen,

.Über diese Aufgabe
System Manager zeigt diese Arten von NVMe over Fabrics Statistiken. Alle Statistiken sind schreibgeschützt und können nicht festgelegt werden.

* *NVMe-Subsystem-Statistik* -- liefert Statistiken für den NVMe-Controller, einschließlich Timeouts und Verbindungsfehlern.
* *RDMA Interface Statistics* -- stellt Statistiken für die RDMA-Schnittstelle bereit, einschließlich empfangener und übertragener Paketinformationen.


Sie können jede dieser Statistiken als RAW-Statistiken oder als Baseline-Statistiken anzeigen. RAW-Statistiken sind alle Statistiken, die seit dem Start der Controller gesammelt wurden. Baseline-Statistiken sind zeitpunktgenaue Statistiken, die seit dem Festlegen der Baseline-Zeit erfasst wurden.

Die NVMe over Fabrics Statistiken können Sie über die Systemseite (Menü:Einstellungen[System]) oder über die Support-Seite aufrufen. In diesen Anweisungen wird der Zugriff auf die Statistiken auf der Support-Seite beschrieben.

.Schritte
. Wählen Sie MENU:Support[Support Center > Diagnose].
. Wählen Sie *View NVMe over Fabrics Statistics* aus.
. Klicken Sie zum Festlegen des Basisplans auf *Neue Baseline festlegen*.
+
Durch das Festlegen der Baseline wird ein neuer Ausgangspunkt für die Erfassung der Statistiken festgelegt. Dieselbe Baseline wird für alle NVMe-Statistiken verwendet.


